# docker run --name nats   -v "$PWD/etc/nats":/etc/nats/   -p 4222:4222   -p 6222:6222   -p 8222:8222   -p 9222:9222   nats:latest   -c /etc/nats/nats.conf
# docker run --name nats   -v "$PWD/etc/nats":/etc/nats/   -p 4222:4222   -p 6222:6222   -p 8222:8222   -p 9222:9222   nats:latest   -c /etc/nats/nats.conf

services:
  nats:
    image: nats:latest
    volumes:
      - ./etc/nats:/etc/nats/
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
      - 9222:9222
    command: -c /etc/nats/nats.conf
